- name: Install Hyper-V, Failover Clustering, Network ATC, DCB
  ansible.windows.win_feature:
    name:
      - Hyper-V
      - Failover-Clustering
      - NetworkATC
      - Data-Center-Bridging
    include_management_tools: true
    state: present

- name: Reboot if required
  ansible.windows.win_reboot:
    reboot_timeout: 1800
  when: ansible_reboot_pending