galaxy_info:
  role_name: disable_firewall
  author: skyler
  description: Disable Windows Firewall profiles (lab use)
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Windows
      versions:
        - all